# Default values for gateway.

controller:
  replicas: 1
  annotations: {}
  # add custom configuration options
  config: {}
  ## Limit the scope of the controller
  ##
  scope:
    enabled: false
    namespace: ""  # defaults to .Release.Namespace
  image:
    repository: kubesphere/nginx-ingress-controller
    tag: "v1.1.0"
    pullPolicy: IfNotPresent
    digest: ""


service:
  ## annotations for Services, used for config Cloud LoadBalancer
  annotations: {}
  type: LoadBalancer

## for nginx controller, same with controller
deployment:
  annotations: {}
  replicas: 1
  resources:
#    limits:
#      cpu: 100m
#      memory: 90Mi
    requests:
      cpu: 100m
      memory: 90Mi

  