---
apiVersion: iam.kubesphere.io/v1alpha2
kind: User
metadata:
  name: admin
  annotations:
    iam.kubesphere.io/uninitialized: "true"
    helm.sh/resource-policy: keep
spec:
  email: admin@kubesphere.io
  password: {{ include "getOrDefaultPass" . | quote }}
status:
  state: Active