services:
  - docker

language: go

go:
  - 1.10

go_import_path: kubesphere.io/kubesphere

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

before_script:
  - dep ensure -v
  - docker --version
  - dep ensure -v

script:
  - make fmt-check && make build

deploy:
  provider: script
  script: bash install/scripts/docker_push
  on:
    branch: master
