services:
  - docker

language: go

dist: xenial

git:
  depth: false

go:
  - "1.13.x"
env:
  - GO111MODULE=on
cache:
  directories:
    - $HOME/gopath/pkg/mod

before_script:
  - docker --version
  - bash hack/install_kubebuilder.sh

script:
  - diff -u <(echo -n) <(gofmt -d ./pkg ./cmd ./tools)
  - make openapi
  - make all && $HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-ci -repotoken $COVERALLS_TOKEN

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - go get golang.org/x/lint/golint

deploy:
  skip_cleanup: true
  provider: script
  script: bash hack/docker_build.sh 
  on:
    branch: master
