services:
  - docker

language: go

dist: xenial

git:
  depth: false

go:
  - "1.12.x"
env:
  - GO111MODULE=on

before_script:
  - docker --version
  - bash hack/install_kubebuilder.sh

script:
  - make all 

deploy:
  skip_cleanup: true
  provider: script
  script: bash hack/docker_build.sh 
  on:
    branch: master
