required = [
    "github.com/emicklei/go-restful",
    "github.com/onsi/ginkgo", # for test framework
    "github.com/onsi/gomega", # for test matchers
    "k8s.io/gengo/examples/defaulter-gen/generators",
    "k8s.io/gengo/examples/deepcopy-gen/generators",
    "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
    "k8s.io/code-generator/cmd/client-gen",
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    "sigs.k8s.io/controller-runtime/pkg/client/config",
    "sigs.k8s.io/controller-runtime/pkg/controller",
    "sigs.k8s.io/controller-runtime/pkg/handler",
    "sigs.k8s.io/controller-runtime/pkg/manager",
    "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
    "sigs.k8s.io/controller-runtime/pkg/source",
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
    "github.com/kubesphere/s2ioperator/pkg/client/clientset/versioned",
    "github.com/kubesphere/s2ioperator/pkg/client/informers/externalversions",
    "github.com/kubesphere/s2ioperator/pkg/apis/devops/v1alpha1",
    "k8s.io/kube-openapi/cmd/openapi-gen"
]


[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/kube-openapi"
  revision = "fd29a9f2f42946ceb3fbd87518e0f2f4343da168"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.13.1"

[[constraint]]
  name="sigs.k8s.io/controller-runtime"
  version="v0.1.7"

[[constraint]]
  name="sigs.k8s.io/controller-tools"
  version="v0.1.7"

[[constraint]]
  name="github.com/kubesphere/s2ioperator"
  version="v0.0.9"

[[override]]
  name="github.com/bifurcation/mint"
  revision="824af65410658916142a7600349144e1289f2110"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false


# To use reference package:
#   vendor/github.com/docker/docker/client/container_commit.go:17: undefined: reference.ParseNormalizedNamed
#   vendor/github.com/docker/docker/client/container_commit.go:25: undefined: reference.TagNameOnly
#   vendor/github.com/docker/docker/client/container_commit.go:30: undefined: reference.FamiliarNam
[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

# To use reference package:
#   vendor/github.com/docker/docker/registry/registry.go:30: cannot call non-function tlsconfig.ServerDefault (type tls.Config)
#   vendor/github.com/docker/docker/registry/registry.go:66: undefined: tlsconfig.SystemCertPool
#   vendor/github.com/docker/docker/registry/registry.go:168: cannot call non-function tlsconfig.ServerDefault (type tls.Config)
#   vendor/github.com/docker/docker/registry/service_v2.go:11: cannot call non-function tlsconfig.ServerDefault (type tls.Config)
[[override]]
  name = "github.com/docker/go-connections"
  version = "0.4.0"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
  version = "v1.4.7"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.5.2"

# offical application controller doesn't limit observe scope to namespace
# use our own version instead
[[constraint]]
  name = "sigs.k8s.io/application"
  source = "https://github.com/kubesphere/application"
  branch = "kubesphere"

[[constraint]]
  name = "github.com/kiali/kiali"
  source = "https://github.com/kubesphere/kiali"
  branch = "kubesphere"

[[constraint]]
  name = "github.com/kubernetes-sigs/application"
  source = "https://github.com/kubesphere/application"
  branch = "kubesphere"

[[constraint]]
  name = "github.com/knative/pkg"
  revision = "cd278f2d3394c865fda66bca12459e879e0279b8"

[[constraint]]
  name = "gopkg.in/igm/sockjs-go.v2"
  version = "2.0.0"

[[constraint]]
  name = "github.com/gocraft/dbr"
  revision = "a0fd650918f6287ffe111d1c7b66bb755ff3be4a"

[[constraint]]
  name = "github.com/kubesphere/sonargo"
  version = "0.0.2"
