
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: ""
  creationTimestamp: null
  name: helmrepos.application.kubesphere.io
spec:
  group: application.kubesphere.io
  names:
    kind: HelmRepo
    listKind: HelmRepoList
    plural: helmrepos
    shortNames:
    - hrepo
    singular: helmrepo
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.name
      name: name
      type: string
    - jsonPath: .metadata.labels.kubesphere\.io/workspace
      name: Workspace
      type: string
    - jsonPath: .spec.url
      name: url
      type: string
    - jsonPath: .status.state
      name: State
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HelmRepo is the Schema for the helmrepoes API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: HelmRepoSpec defines the desired state of HelmRepo
            properties:
              credential:
                description: helm repo credential
                properties:
                  accessKeyID:
                    type: string
                  caFile:
                    description: verify certificates of HTTPS-enabled servers using
                      this CA bundle
                    type: string
                  certFile:
                    description: identify HTTPS client using this SSL certificate
                      file
                    type: string
                  insecureSkipTLSVerify:
                    description: skip tls certificate checks for the repository, default
                      is ture
                    type: boolean
                  keyFile:
                    description: identify HTTPS client using this SSL key file
                    type: string
                  password:
                    description: chart repository password
                    type: string
                  secretAccessKey:
                    type: string
                  username:
                    description: chart repository username
                    type: string
                type: object
              description:
                description: chart repo description from frontend
                type: string
              name:
                description: name of the repo
                type: string
              syncPeriod:
                description: sync period in seconds, no sync when SyncPeriod=0, the
                  minimum SyncPeriod is 180s
                type: integer
              url:
                description: helm repo url
                type: string
              version:
                description: expected repo version, when this version is not equal
                  status.version, the repo need upgrade this filed should be modified
                  when any filed of the spec modified.
                type: integer
            required:
            - name
            - url
            type: object
          status:
            description: HelmRepoStatus defines the observed state of HelmRepo
            properties:
              data:
                description: repo index
                type: string
              lastUpdateTime:
                description: status last update time
                format: date-time
                type: string
              state:
                description: current state of the repo, successful, failed or syncing
                type: string
              syncState:
                description: sync state list of history, which will store at most
                  10 state
                items:
                  properties:
                    message:
                      description: A human readable message indicating details about
                        why the repo is in this state.
                      type: string
                    state:
                      description: 'last sync state, valid state are: "failed", "success",
                        and ""'
                      type: string
                    syncTime:
                      format: date-time
                      type: string
                  required:
                  - syncTime
                  type: object
                type: array
              version:
                description: if status.version!=spec.Version, we need sync the repo
                  now
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
