# Use the 'create api' subcommand to add watches to this file.
- group: gateway.kubesphere.io
  version: v1alpha1
  kind: Nginx
  chart: /var/helm-charts/ingress-nginx
- group: gateway.kubesphere.io
  version: v1alpha1
  kind: Gateway
  chart: /var/helm-charts/gateway
# uncomment the following 2 lines, if only allow to run global scope or namespaced scope.
# Leave the option to CR, when allow to run global and namespaced together.
  # overrideValues:
  #   controller.scope.enabled: $SCOPE_ENABLED
#+kubebuilder:scaffold:watch
